# Numpy
https://numpy.org/devdocs/user/quickstart.html

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Importar-Numpy" data-toc-modified-id="Importar-Numpy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Importar Numpy</a></span></li><li><span><a href="#Crear-matrices" data-toc-modified-id="Crear-matrices-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Crear matrices</a></span></li><li><span><a href="#Operaciones" data-toc-modified-id="Operaciones-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Operaciones</a></span></li><li><span><a href="#Selecciones" data-toc-modified-id="Selecciones-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Selecciones</a></span></li><li><span><a href="#Guardar-matrices" data-toc-modified-id="Guardar-matrices-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Guardar matrices</a></span></li></ul></div>

### Importar Numpy

In [1]:
#Importar numpy
import numpy as np

### Crear matrices

In [2]:
#Crear una matriz (array)
list_1 = [1,2,3,4]
array1 = np.array(list_1)

In [3]:
#Mostrar la matriz
array1

array([1, 2, 3, 4])

In [4]:
#Crear una matriz con 2 dimensiones
list_2 = [[1,2,3,4],[5,6,7,8]]
array2 = np.array(list_2)
#Mostrar la matriz
array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
#Crear una matriz con 3 dimensiones
list_3 = [[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]]
array3 = np.array(list_3)
#Mostrar la matriz
array3

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [6]:
#Calcular las dimensiones de las matrices
print(array1.shape)
print(array2.shape)
print(array3.shape)

(4,)
(2, 4)
(2, 2, 4)


In [7]:
#Mostrar el tipo de datos de la matriz
array2.dtype

dtype('int64')

In [8]:
#Matrices de otros tipos
array4=np.array(['Hola','Mundo'])
array5=np.array([1.,2.])
print(array4.dtype)
print(array5.dtype)

<U5
float64


Otros tipos de datos
https://www.i2tutorials.com/numpy-tutorial/numpy-data-types/

In [9]:
#Convertir de un tipo a otro
array6=array3.astype(float)
print(array6.dtype)
array6=array3.astype(np.float32)
print(array6.dtype)

float64
float32


In [10]:
#Crear una matriz de ceros
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
#Crear una matriz de unos
np.ones([5,5])


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
#Crear una matriz de identidad
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
#Crear una serie de numeros
np.arange(5)

array([0, 1, 2, 3, 4])

In [14]:
#Crear un espacio de numeros
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
arr = np.arange(125)
print(arr.shape)
arr

(125,)


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124])

In [16]:
#Cambiar la forma de un array
arr2=arr.reshape((5,5,5))
print(arr2.shape)
arr2

(5, 5, 5)


array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124]]])

### Operaciones

In [17]:
#Suma
array1=np.ones([5,5])
array1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
array1+1

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [19]:
array1+5

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [20]:
array2=np.array([1,2,3,4,5])

In [21]:
array1+array2

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [22]:
array3=np.eye(5)
array3

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
array1+array3

array([[2., 1., 1., 1., 1.],
       [1., 2., 1., 1., 1.],
       [1., 1., 2., 1., 1.],
       [1., 1., 1., 2., 1.],
       [1., 1., 1., 1., 2.]])

In [24]:
#Resta
array1-array3

array([[0., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1.],
       [1., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0.]])

In [25]:
#Multiplicacion

In [26]:
array1*2

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [27]:
array1*np.array([1,2,3,4,5])

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [28]:
array1*np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
#Division
array1/2

array([[0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5]])

In [30]:
array1/np.array([1,2,3,4,5])

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [1.        , 0.5       , 0.33333333, 0.25      , 0.2       ]])

In [31]:
array1/np.eye(5)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ 1., inf, inf, inf, inf],
       [inf,  1., inf, inf, inf],
       [inf, inf,  1., inf, inf],
       [inf, inf, inf,  1., inf],
       [inf, inf, inf, inf,  1.]])

In [32]:
#Exponenciacion
array1=np.array([[1,2,3],[4,5,6]])
array1**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [33]:
#e^x
np.exp(array1)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [34]:
#Raiz quadrada
np.sqrt(array1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [35]:
#Maximo y minimo
np.max(array1),np.min(array1)

(6, 1)

In [36]:
#Promedio
np.mean(array1)

3.5

Otras operaciones
https://numpy.org/doc/stable/reference/ufuncs.html

In [37]:
#Transpuesta
array1=np.array([[1,2],[3,4]])
array1

array([[1, 2],
       [3, 4]])

In [38]:
array2=array1.T
array2

array([[1, 3],
       [2, 4]])

In [39]:
#Transposicion en 3D
arr=np.arange(27).reshape(3,3,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [40]:
arr.T
#0->2
#2->0

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [41]:
arr.transpose((0,2,1))
#0->0
#2->1
#1->2

array([[[ 0,  3,  6],
        [ 1,  4,  7],
        [ 2,  5,  8]],

       [[ 9, 12, 15],
        [10, 13, 16],
        [11, 14, 17]],

       [[18, 21, 24],
        [19, 22, 25],
        [20, 23, 26]]])

In [42]:
#Dot product (producto interno)
array1=np.array([[1,2],[3,4]])
np.dot(array1,array1)

array([[ 7, 10],
       [15, 22]])

In [43]:
#Cross product (producto cruz)
array1=np.array([1,0,0])
array2=np.array([0,1,0])
np.cross(array1,array2)

array([0, 0, 1])

### Selecciones

In [44]:
#Seleccionar parte de una tabla
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
#Obtener un valor
arr[5]

5

In [46]:
#Obtener valores en un rango
arr[1:5]

array([1, 2, 3, 4])

In [47]:
#Dar valores en un rango
arr[0:3]=100
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [48]:
#Tomar una parte del array
x=arr[5:7]
x

array([5, 6])

In [49]:
#Cuando se modifica una parte
x[:]=2000
x

array([2000, 2000])

In [50]:
#Tambien se modifica el array 
#Los valores no se copian, son parte del array
arr

array([ 100,  100,  100,    3,    4, 2000, 2000,    7,    8,    9,   10])

In [51]:
#Copiar un array
arr = np.arange(0,11)
arr2=arr.copy()
arr,arr2

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [52]:
arr[:]=1
arr,arr2

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [53]:
#En arrays 2D
arr_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
#Seleccionar fila
arr_2D[0]

array([1, 2, 3])

In [55]:
#Seleccionar fila
arr_2D[0,:]

array([1, 2, 3])

In [56]:
#Seleccionar columna
arr_2D[:,0]

array([1, 4, 7])

In [57]:
#Seleccionar ultima columna
arr_2D[:,-1]

array([3, 6, 9])

In [58]:
#Seleccionarun solo valor
arr_2D[0,-1]

3

In [59]:
#Seleccionar varias filas
arr_2D[[0,-1]]

array([[1, 2, 3],
       [7, 8, 9]])

In [60]:
#Seleccionar varias filas y columnas
arr_2D[[0,-1]].T[[0,-1]].T

array([[1, 3],
       [7, 9]])

In [61]:
#Seleccionar rangos
arr_2D[:2,-2:]

array([[2, 3],
       [5, 6]])

In [62]:
#Seleccionar valores particulares
arr_2D[(0,1,2),(0,1,2)]

array([1, 5, 9])

### Guardar matrices

In [63]:
arr = np.arange(5)

In [64]:
np.save('saved_array',arr)
np.load('saved_array.npy')

array([0, 1, 2, 3, 4])

In [65]:
np.savez('dos_arrays.npz',x=arr,y=arr)
np.load('dos_arrays.npz')

In [66]:
arrays=np.load('dos_arrays.npz')
arrays['x']

array([0, 1, 2, 3, 4])